### ISSUE TITLE
Check internal.yml and internal_test.yml if grpc is right configured

### ISSUE THREAD

**Issue by Sddilora** [octoposprime/op-be-shared#19]
```yml
grpc:
  logger_host: "logger"
  logger_port: "18081"
```

We have designated the host as "op-be-*" and the port as 18080 in other parts of the services. However, I am unsure if these are correct here.
